### ISSUE TITLE
File without extension can not be detected by shebang (?)

### ISSUE THREAD

**Issue by fitrh** [nathom/filetype.nvim#10]
Sometimes, I have a bash script with no extension and just put a shebang to make vim detect the file type, but with this plugin, does not seem possible anymore, is this to be expected ?

**Comment by ashincoder** [comment]
For me too. It doesn't detect the filetype for my zsh files.

**Comment by uga-rosa** [comment]
Could you try #18?

**Comment by fitrh** [comment]
@uga-rosa i have tested your fork with `bash` and `node` shebang and it works

**Comment by ashincoder** [comment]
> Could you try #18?

@uga-rosa It works for me now. Thank you for the fix.

**Comment by uga-rosa** [comment]
Merged into the dev branch.

**Comment by nathom** [comment]
Shebang has been merged into `main`.
