### ISSUE TITLE
[feat]: lazy loaded with `setup` field

### ISSUE THREAD

**Issue by younger-1** [nathom/filetype.nvim#12]
I would like to specify `vim.g.did_load_filetypes` in `setup` field like below because it is more convenient to manage. But this will cause the default `filetype.vim` in `$VIMRUNTIME` be sourced before the variable be set.

```lua
-- use packer
{
  "nathom/filetype.nvim",
  -- Do not source the default filetype.vim
  setup = function()
    vim.g.did_load_filetypes = 1
  end,
},
```

Is it possible to achieve it?

**Comment by nathom** [comment]
I don't think this is possible. That line has to be executed before the runtime files are sourced, and packer sources everything *after* the runtime files. You should check in with the maintainer of packer.nvim to see if there is a workaround.

**Comment by younger-1** [comment]
Thanks for your reply!
