### ISSUE TITLE
shebang not work with dotfiles

### ISSUE THREAD

**Issue by aspeddro** [nathom/filetype.nvim#37]
filetype.nvim no work with `.utils`

![image](https://user-images.githubusercontent.com/16160544/138394915-6036245e-8dc4-4a5a-ac47-5f9727c6ab54.png)

`:lua print(vim.bo.filetype)` return `util`

Renaming `.utils` to `utils` it works.
![image](https://user-images.githubusercontent.com/16160544/138394999-c6ded686-4419-4d7e-b919-2763a96d9b8d.png)

**Comment by nathom** [comment]
Should be fixed in latest version.
