### ISSUE TITLE
Overrides ftdetect from filetype plugins

### ISSUE THREAD

**Issue by clason** [nathom/filetype.nvim#41]
This may be a fundamental limitation of this approach rather than a bug that should be fixed, but I wanted to report it nevertheless (especially considering the possibility of upstreaming it):

When `filetype.nvim` is installed, it (correctly) disables the built-in `filetype.vim`. However, it also disables all `ftdetect/foo.vim` in `runtimepath`, which means that filetype plugins like https://github.com/lervag/vimtex which extend or correct Vim's detection logic no longer work.

Of course, I can mirror what the plugin's `ftdetect/` scripts are doing in my setup, but a more conservative (and still as performant) approach would be to disable only `filetype.vim` but keep sourcing `ftdetect/` scripts (which, however, may require changes in core so be only relevant for an upstream version).

**Comment by gegoune** [comment]
Related https://github.com/nathom/filetype.nvim/issues/9

**Comment by clason** [comment]
Agreed. Can you reopen that issue so I can close this as duplicate?

**Comment by clason** [comment]
Duplicate of #9
