### ISSUE TITLE
builtin_map  does not exists and makes  shabang detection to fail

### ISSUE THREAD

**Issue by leiserfg** [nathom/filetype.nvim#48]
https://github.com/nathom/filetype.nvim/blob/295e1074fa94e588aa7c2fc4e2e1367af508c4be/lua/filetype/init.lua#L240

**Comment by leiserfg** [comment]
While trying to fix this I noticed that there are several instances of death code (redefined functions/functions that are never called...), should I correct them or are they WIP code?
For instance `try_all_maps` is not called and has errors, `analyze_shebang` has two definitions.

**Comment by nathom** [comment]
This issue, along with the dead code was the result of a pretty bad merge that I made. Thanks for the fix.

**Comment by leiserfg** [comment]
It will be nice to have something like  https://github.com/vitalk/vim-shebang as in some cases the program and the filetype name don't match.
