### ISSUE TITLE
Detect file type based on file contents

### ISSUE THREAD

**Issue by ElSamhaa** [nathom/filetype.nvim#69]
The easiest way to enable this -- until implemented -- is to pass the file path/name to the functions under `function_extensions` for instance.

This will allow for custom logic provided by the user, based on which he can set the filetype eventually before the function returns.

Currently, this is how I do it:
```lua
local filename = vim.api.nvim_buf_get_name(0)

require("filetype").setup {
  overrides = {
    function_extensions = {
      ["yaml"] = function()
        file = io.open(filename, "r")
        filecontent = file:read("*all")
        if string.find(filecontent, "{{") then
          vim.bo.filetype = "gotexttmpl"
        end
        file.close()
      end,
    }
  },
}
```

But the above fails to run when opening a buffer after starting a neovim session.

**Comment by ObserverOfTime** [comment]
It should work if you place the call to `nvim_buf_get_name` *inside* the function.

**Comment by ElSamhaa** [comment]
@ObserverOfTime You're right :sweat_smile: . You can close this issue.

Do you know where the `print` output goes to?, It doesn't appear under with `:messages`.

**Comment by ObserverOfTime** [comment]
Use `vim.notify` instead.

**Comment by ObserverOfTime** [comment]
Also, you can use `vim.api.nvim_buf_get_lines` instead of manually opening the file.

**Comment by ElSamhaa** [comment]
Thanks
