### ISSUE TITLE
E5108: attempt to call a method 'byte' (a nil value)

### ISSUE THREAD

**Issue by aspeddro** [nathom/filetype.nvim#75]
```sh
nvim init.lua
```

![image](https://user-images.githubusercontent.com/16160544/155345344-2f1334cc-9625-42b7-8c16-5fe11d139d55.png)

**Comment by aspeddro** [comment]
closing, it was a problem with https://github.com/p00f/nvim-ts-rainbow/issues/94

**Comment by Chaitanyabsprip** [comment]
@aspeddro I am getting the same issue, how did you solve it?

**Comment by aspeddro** [comment]
Run `:PackerCompile`

**Comment by Chaitanyabsprip** [comment]
done that a few times, doesn't fix it

**Comment by Chaitanyabsprip** [comment]
can you share your config please

**Comment by aspeddro** [comment]
@Chaitanyabsprip, sorry for delay.

https://github.com/aspeddro/dotfiles/blob/main/.config/nvim/lua/user/plugins/treesitter.lua
