### ISSUE TITLE
filetype is nil when open a shell file on nvim 0.9

### ISSUE THREAD

**Issue by BYT0723** [nathom/filetype.nvim#95]
- appear some message when open a shell file
![图片](https://user-images.githubusercontent.com/59989961/230817390-56f3cbed-d4d9-478d-befd-f36800fba10e.png)

- then `set filetype`
![图片](https://user-images.githubusercontent.com/59989961/230817483-50164e44-33a5-467b-bf99-99e109f936e3.png)

**Comment by kohane27** [comment]
Duplicate: https://github.com/nathom/filetype.nvim/issues/94
